import { ApiSpec, Endpoint } from '../types';

export function generateReadme(spec: ApiSpec): string {
    const sections: string[] = [];

    // Title
    sections.push(`# ${spec.title} — Quickstart Guide\n`);
    sections.push(`> Auto-generated by HelloAPI\n`);
    if (spec.description) {
        sections.push(`${spec.description}\n`);
    }

    // Auth
    sections.push(`## 🔐 Authentication\n`);
    sections.push(renderAuth(spec));

    // Env
    sections.push(`## ⚙️ Environment Variables\n`);
    sections.push(renderEnvVars(spec));

    // Install
    sections.push(`## 📦 Installation\n`);
    sections.push(renderInstall());

    // First Request
    sections.push(`## 🚀 First Request\n`);
    sections.push(renderFirstRequest(spec));

    // Pagination
    if (spec.paginationHints.length > 0) {
        sections.push(`## 📄 Pagination\n`);
        sections.push(renderPagination(spec));
    }

    // Errors
    sections.push(`## ❌ Error Handling\n`);
    sections.push(renderErrors(spec));

    // Rate Limits
    if (spec.rateLimitHints.length > 0) {
        sections.push(`## ⏱️ Rate Limiting\n`);
        sections.push(renderRateLimits(spec));
    }

    // Endpoints Summary
    sections.push(`## 📋 Endpoints Summary\n`);
    sections.push(renderEndpointSummary(spec));

    // Troubleshooting
    sections.push(`## 🔧 Troubleshooting\n`);
    sections.push(renderTroubleshooting());

    return sections.join('\n');
}

function renderAuth(spec: ApiSpec): string {
    const a = spec.auth;
    switch (a.type) {
        case 'bearer':
            return `This API uses **Bearer Token** authentication.\n\nInclude the following header in every request:\n\n\`\`\`\nAuthorization: Bearer YOUR_API_TOKEN\n\`\`\`\n`;
        case 'apiKey':
            if (a.headerName) {
                return `This API uses an **API Key** in the \`${a.headerName}\` header.\n\n\`\`\`\n${a.headerName}: YOUR_API_KEY\n\`\`\`\n`;
            }
            if (a.queryParamName) {
                return `This API uses an **API Key** as a query parameter: \`${a.queryParamName}\`.\n\n\`\`\`\n${spec.baseUrl}/endpoint?${a.queryParamName}=YOUR_API_KEY\n\`\`\`\n`;
            }
            return `This API uses an **API Key**. ${a.description || ''}\n`;
        case 'basic':
            return `This API uses **Basic Authentication**.\n\n\`\`\`\nAuthorization: Basic base64(username:password)\n\`\`\`\n`;
        case 'oauth2':
            return `This API uses **OAuth 2.0**. You will need to obtain an access token through the OAuth flow before making requests.\n\n> TODO: Check the API provider's documentation for the exact OAuth endpoints and scopes required.\n`;
        case 'none':
            return `This API does not require authentication (public API).\n`;
        default:
            return `> TODO: Authentication method could not be determined. Check the API documentation.\n`;
    }
}

function renderEnvVars(spec: ApiSpec): string {
    const vars: string[] = [];
    vars.push(`Create a \`.env\` file with the following variables:\n`);
    vars.push('```bash');
    vars.push(`API_BASE_URL=${spec.baseUrl}`);
    if (spec.auth.type === 'bearer') vars.push('API_TOKEN=your_token_here');
    else if (spec.auth.type === 'apiKey') vars.push('API_KEY=your_api_key_here');
    else if (spec.auth.type === 'basic') {
        vars.push('API_USERNAME=your_username');
        vars.push('API_PASSWORD=your_password');
    }
    vars.push('```\n');
    return vars.join('\n');
}

function renderInstall(): string {
    return `### Python\n\n\`\`\`bash\npip install requests python-dotenv\n\`\`\`\n\n### TypeScript / Node.js\n\n\`\`\`bash\nnpm install axios dotenv\n\`\`\`\n`;
}

function renderFirstRequest(spec: ApiSpec): string {
    const getEndpoint = spec.endpoints.find(e => e.method === 'GET' && !e.path.includes('{'));
    if (!getEndpoint) {
        if (spec.endpoints.length > 0) {
            return renderCurlForEndpoint(spec, spec.endpoints[0]);
        }
        return '> TODO: No suitable first-request endpoint was found.\n';
    }
    return renderCurlForEndpoint(spec, getEndpoint);
}

function renderCurlForEndpoint(spec: ApiSpec, ep: Endpoint): string {
    let curl = `Try this request to verify your setup:\n\n\`\`\`bash\ncurl`;
    if (ep.method !== 'GET') curl += ` -X ${ep.method}`;
    curl += ` "${spec.baseUrl}${ep.path}"`;
    curl += renderAuthHeaders(spec);
    curl += `\n\`\`\`\n`;
    curl += `\nExpected: **${ep.responses[0]?.statusCode || '200'}** — ${ep.responses[0]?.description || 'Success'}\n`;
    return curl;
}

function renderAuthHeaders(spec: ApiSpec): string {
    const a = spec.auth;
    if (a.type === 'bearer') return ` \\\n  -H "Authorization: Bearer $API_TOKEN"`;
    if (a.type === 'apiKey' && a.headerName) return ` \\\n  -H "${a.headerName}: $API_KEY"`;
    if (a.type === 'basic') return ` \\\n  -u "$API_USERNAME:$API_PASSWORD"`;
    return '';
}

function renderPagination(spec: ApiSpec): string {
    const hint = spec.paginationHints[0];
    const lines: string[] = [];
    lines.push(`This API uses **${hint.type}-based** pagination.\n`);
    lines.push(`Parameters: ${hint.parameters.map(p => `\`${p}\``).join(', ')}\n`);

    if (hint.type === 'offset') {
        lines.push(`\`\`\`bash\n# Fetch page by page\ncurl "${spec.baseUrl}/resource?offset=0&limit=20"\ncurl "${spec.baseUrl}/resource?offset=20&limit=20"\n\`\`\`\n`);
    } else if (hint.type === 'cursor') {
        lines.push(`\`\`\`bash\n# First page\ncurl "${spec.baseUrl}/resource"\n# Next page — use the cursor from the response\ncurl "${spec.baseUrl}/resource?cursor=CURSOR_VALUE"\n\`\`\`\n`);
    } else {
        lines.push(`\`\`\`bash\ncurl "${spec.baseUrl}/resource?page=1&per_page=20"\n\`\`\`\n`);
    }
    return lines.join('\n');
}

function renderErrors(_spec: ApiSpec): string {
    return `| Status | Meaning | Common Fix |
|--------|---------|------------|
| **400** | Bad Request | Check request body format and required fields |
| **401** | Unauthorized | Verify your API key / token is correct and not expired |
| **403** | Forbidden | Check permissions — your key may not have access to this resource |
| **404** | Not Found | Verify the endpoint path and any resource IDs |
| **429** | Rate Limited | Slow down requests — implement exponential backoff |
| **500** | Server Error | Retry after a short delay — this is usually temporary |
`;
}

function renderRateLimits(spec: ApiSpec): string {
    const hint = spec.rateLimitHints[0];
    return `This API enforces rate limits. If you receive a **${hint.statusCode}** response:\n\n1. Check the \`${hint.retryHeader || 'Retry-After'}\` header for wait time\n2. Implement exponential backoff\n3. Cache responses when possible\n\n\`\`\`python\nimport time\n\ndef request_with_backoff(url, headers, max_retries=3):\n    for attempt in range(max_retries):\n        response = requests.get(url, headers=headers)\n        if response.status_code == 429:\n            wait = int(response.headers.get('Retry-After', 2 ** attempt))\n            time.sleep(wait)\n            continue\n        return response\n    raise Exception("Max retries exceeded")\n\`\`\`\n`;
}

function renderEndpointSummary(spec: ApiSpec): string {
    if (spec.endpoints.length === 0) return '> No endpoints detected.\n';
    const lines: string[] = ['| Method | Path | Description |', '|--------|------|-------------|'];
    for (const ep of spec.endpoints.slice(0, 20)) {
        lines.push(`| \`${ep.method}\` | \`${ep.path}\` | ${ep.summary || '—'} |`);
    }
    if (spec.endpoints.length > 20) {
        lines.push(`\n_...and ${spec.endpoints.length - 20} more endpoints._\n`);
    }
    return lines.join('\n') + '\n';
}

function renderTroubleshooting(): string {
    return `### "Connection refused" / Cannot reach host
- Verify \`API_BASE_URL\` is correct
- Check if the API requires VPN or IP whitelisting

### "401 Unauthorized" on every request
- Double-check your credentials in \`.env\`
- Ensure the token/key has not expired
- Verify the header name matches what the API expects

### "403 Forbidden"
- Your credentials may lack the required scope or role
- Contact the API provider to verify access

### "429 Too Many Requests"
- Add delays between requests
- Implement retry with exponential backoff
- Check if there is a rate limit tier you can upgrade to

### Empty or unexpected response
- Check if the endpoint requires specific query parameters
- Verify the \`Content-Type\` header matches the request body format
- Look at the full response headers for clues
`;
}
