import { ApiSpec } from '../types';

export function generateTypeScriptClient(spec: ApiSpec): string {
    const lines: string[] = [];

    lines.push(`/**
 * ${spec.title} — TypeScript Starter Client
 * Auto-generated by HelloAPI
 */

import axios, { AxiosInstance, AxiosResponse } from "axios";

${getAuthInterface(spec)}

class ${sanitizeClassName(spec.title)}Client {
  private client: AxiosInstance;
  private maxRetries = 3;

  constructor(${getConstructorParams(spec)}) {
    this.client = axios.create({
      baseURL: baseUrl,
      headers: ${getHeadersObj(spec)},
    });

    // Retry interceptor for rate limiting
    this.client.interceptors.response.use(
      (response) => response,
      async (error) => {
        const config = error.config;
        if (
          error.response?.status === 429 &&
          (!config._retryCount || config._retryCount < this.maxRetries)
        ) {
          config._retryCount = (config._retryCount || 0) + 1;
          const retryAfter = parseInt(error.response.headers["retry-after"] || "1", 10);
          await new Promise((resolve) => setTimeout(resolve, retryAfter * 1000));
          return this.client(config);
        }
        throw error;
      }
    );
  }
`);

    // Generate methods for each endpoint
    for (const ep of spec.endpoints) {
        const methodName = sanitizeMethodName(ep.operationId || `${ep.method.toLowerCase()}_${ep.path}`);
        const pathParams = ep.parameters.filter(p => p.in === 'path');
        const queryParams = ep.parameters.filter(p => p.in === 'query');
        const hasBody = !!ep.requestBody;

        const params: string[] = [];
        for (const p of pathParams) {
            params.push(`${sanitizeTsVar(p.name)}: string`);
        }
        if (queryParams.length > 0) {
            params.push(`params?: { ${queryParams.map(p => `${sanitizeTsVar(p.name)}?: string`).join('; ')} }`);
        }
        if (hasBody) {
            params.push('data?: Record<string, unknown>');
        }

        let pathStr = ep.path;
        for (const p of pathParams) {
            pathStr = pathStr.replace(`{${p.name}}`, `\${${sanitizeTsVar(p.name)}}`);
        }

        lines.push(`
  /** ${ep.summary || `${ep.method} ${ep.path}`} */
  async ${methodName}(${params.join(', ')}): Promise<AxiosResponse> {
    return this.client.${ep.method.toLowerCase()}(\`${pathStr}\`${hasBody ? ', data' : queryParams.length > 0 && !hasBody ? ', { params }' : ''}${hasBody && queryParams.length > 0 ? ', { params }' : ''});
  }`);
    }

    lines.push(`
}

export default ${sanitizeClassName(spec.title)}Client;

// ─── Usage Example ───
`);

    lines.push(`/*
const client = new ${sanitizeClassName(spec.title)}Client(${getExampleArgs(spec)});
`);

    const firstGet = spec.endpoints.find(e => e.method === 'GET' && !e.path.includes('{'));
    if (firstGet) {
        const name = sanitizeMethodName(firstGet.operationId || `${firstGet.method.toLowerCase()}_${firstGet.path}`);
        lines.push(`const response = await client.${name}();`);
        lines.push(`console.log(response.data);`);
    }

    lines.push(`*/`);

    return lines.join('\n');
}

// ─── Helpers ───

function sanitizeClassName(name: string): string {
    const clean = name.replace(/[^a-zA-Z0-9]/g, '');
    return (clean.charAt(0).toUpperCase() + clean.slice(1)) || 'Api';
}

function sanitizeMethodName(name: string): string {
    const parts = name
        .replace(/[{}\/\-.]/g, '_')
        .replace(/_{2,}/g, '_')
        .replace(/^_|_$/g, '')
        .toLowerCase()
        .split('_');
    return parts[0] + parts.slice(1).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function sanitizeTsVar(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function getAuthInterface(spec: ApiSpec): string {
    if (spec.auth.type === 'none') return '';
    return `interface ClientConfig {
  baseUrl?: string;
  ${spec.auth.type === 'bearer' ? 'token: string;' : ''}${spec.auth.type === 'apiKey' ? 'apiKey: string;' : ''}${spec.auth.type === 'basic' ? 'username: string;\n  password: string;' : ''}
}\n`;
}

function getConstructorParams(spec: ApiSpec): string {
    const parts = [`baseUrl: string = "${spec.baseUrl}"`];
    if (spec.auth.type === 'bearer') parts.push('token: string = process.env.API_TOKEN || ""');
    else if (spec.auth.type === 'apiKey') parts.push('apiKey: string = process.env.API_KEY || ""');
    return parts.join(', ');
}

function getHeadersObj(spec: ApiSpec): string {
    if (spec.auth.type === 'bearer') return '{ Authorization: `Bearer ${token}` }';
    if (spec.auth.type === 'apiKey' && spec.auth.headerName) return `{ "${spec.auth.headerName}": apiKey }`;
    return '{}';
}

function getExampleArgs(spec: ApiSpec): string {
    if (spec.auth.type === 'bearer') return '"https://api.example.com", "YOUR_TOKEN"';
    if (spec.auth.type === 'apiKey') return '"https://api.example.com", "YOUR_API_KEY"';
    return '';
}
